# Insert IP, SSH key Path If you not use pem key, you can remove ansible_ssh_private_key_file={$KEY_PATH} and add password={$PASSWORD}
[master]
node1 ansible_host={$MASTER_IP} ansible_user={$MASTER_USER} ansible_ssh_private_key_file={$KEY_PATH}
#node1 ansible_host={$MASTER_IP} ansible_user={$MASTER_USER} password={$PASSWORD}

[workers]
node2 ansible_host={$WORKER_IP} ansible_user={$WORKER_USER} ansible_ssh_private_key_file={$KEY_PATH}
#node2 ansible_host={$WORKER_IP} ansible_user={$WORKER_USER} password={$PASSWORD}

[k8s_all:children]
master
workers
