---
# 1. Common tasks for all nodes
- name: Common setup for all nodes
  hosts: all
  become: yes
  roles:
    - common

# 2. Master node specific tasks
- name: Kubernetes control plane configuration
  hosts: master
  become: yes
  roles:
    - k8s_master
 
# 3. Worker nodes specific tasks
- name: worker node configuration
  hosts: workers
  become: yes
  roles:
    - k8s_worker
