---
# 1. Default setup for all nodes (masters + workers)
- name: SWAP disable and kernel settings
  shell: |
    swapoff -a
    sed -i '/swap/s/^/#/' /etc/fstab

- name: auto load kernel modules at boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: load kernel modules (network bridge related)
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: kernel parameter settings (IP forwarding, etc.)
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }



# 2. Container runtime and Kubernetes packages installation (common for both masters and workers) works in Ubuntu/Debian based systems
- name: essential packages installation (apt)
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release, lvm2]
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: GPG keyring directory creation
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: Docker GPG Key Download
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Docker Repository Addition
  apt_repository:
    repo: >
      deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable
    filename: docker
    state: present
  when: ansible_os_family == "Debian"

- name: containerd.io Package Installation
  apt:
    name: containerd.io
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Systemd cgroup Driver Configuration for containerd
  template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
  notify: restart_containerd
  when: ansible_os_family == "Debian"

- name: Kubernetes GPG Key Download
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Kubernetes Repository Addition
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/ /"
    state: present
    filename: kubernetes
  when: ansible_os_family == "Debian"

- name: kubelet, kubeadm, kubectl installation
  apt:
    name: [kubelet, kubeadm, kubectl]
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: kubelet, kubeadm, kubectl version pinning (prevent automatic updates)
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: [kubelet, kubeadm, kubectl]
  when: ansible_os_family == "Debian"

  # 3. Container runtime and Kubernetes packages installation (common for both masters and workers) works in Redhat/CentOS based systems
- name: Selinux configuration to permissive mode (for kubelet and containerd compatibility)
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

- name: Selinux configuration file update to permissive mode (for persistence across reboots)
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
  when: ansible_os_family == "RedHat"

- name: RedHat based systems - essential packages installation
  dnf:
    name: [dnf-utils, device-mapper-persistent-data, lvm2, dnf-plugins-core]
    state: present
  when: ansible_os_family == "RedHat"

- name: Docker repository addition
  get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: containerd.io installation
  dnf:
    name: containerd.io
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Containerd configuration for systemd cgroup driver
  template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
  notify: restart_containerd
  when: ansible_os_family == "RedHat"

- name: Kubernetes repository file creation
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl
  when: ansible_os_family == "RedHat"

- name: kubelet, kubeadm, kubectl installation
  dnf:
    name: [kubelet, kubeadm, kubectl]
    state: present
    disable_excludes: kubernetes
  when: ansible_os_family == "RedHat"

- name: kubelet start and enable
  systemd:
    name: kubelet
    enabled: yes
    state: started