- name: kube init check
  stat:
    path: /etc/kubernetes/admin.conf
  register: kube_init_check

- name: kubeadm initiation
  command: >
    kubeadm init
    --pod-network-cidr=10.0.0.0/16
    --apiserver-advertise-address={{ ansible_host }}
  when: not kube_init_check.stat.exists
  register: kubeadm_init_output

- name: .kube directory creation (root home)
  file:
    path: ~/.kube
    state: directory
    mode: '0755'

- name: admin.conf copy to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0600'

- name: Calico network plugin application
  become: true
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.7/manifests/calico.yaml
  when: not kube_init_check.stat.exists

- name: Create join command for worker nodes
  become: true
  command: kubeadm token create --print-join-command
  register: join_command_raw
  when: inventory_hostname == groups['master'][0]

- name: declare join command as a fact for worker nodes
  set_fact:
    join_command: "{{ join_command_raw.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname == groups['master'][0]